package neu.edu.entity;
// Generated Dec 10, 2017 9:50:59 PM by Hibernate Tools 5.2.3.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * CreatorIdea generated by hbm2java
 */
@Entity
@Table(name = "creatoridea")
public class CreatorIdea implements java.io.Serializable {

	private Integer ideaId;
	private User user;
	private String ideaName;
	private String ideaDesc;
	private int targetAmount;
	private int categoryId;

	public CreatorIdea() {
	}

	public CreatorIdea(User user, String ideaName, int targetAmount, int categoryId) {
		this.user = user;
		this.ideaName = ideaName;
		this.targetAmount = targetAmount;
		this.categoryId = categoryId;
	}

	public CreatorIdea(User user, String ideaName, String ideaDesc, int targetAmount, int categoryId) {
		this.user = user;
		this.ideaName = ideaName;
		this.ideaDesc = ideaDesc;
		this.targetAmount = targetAmount;
		this.categoryId = categoryId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idea_id", unique = true, nullable = false)
	public Integer getIdeaId() {
		return this.ideaId;
	}

	public void setIdeaId(Integer ideaId) {
		this.ideaId = ideaId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_id", nullable = false)
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@Column(name = "idea_name", nullable = false, length = 45)
	public String getIdeaName() {
		return this.ideaName;
	}

	public void setIdeaName(String ideaName) {
		this.ideaName = ideaName;
	}

	@Column(name = "idea_desc", length = 100)
	public String getIdeaDesc() {
		return this.ideaDesc;
	}

	public void setIdeaDesc(String ideaDesc) {
		this.ideaDesc = ideaDesc;
	}

	@Column(name = "target_amount", nullable = false)
	public int getTargetAmount() {
		return this.targetAmount;
	}

	public void setTargetAmount(int targetAmount) {
		this.targetAmount = targetAmount;
	}

	@Column(name = "category_id", nullable = false)
	public int getCategoryId() {
		return this.categoryId;
	}

	public void setCategoryId(int categoryId) {
		this.categoryId = categoryId;
	}

}
