package neu.edu.entity;
// Generated Dec 10, 2017 9:50:59 PM by Hibernate Tools 5.2.3.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * FunderPayment generated by hbm2java
 */
@Entity
@Table(name = "funderpayment")
public class FunderPayment implements java.io.Serializable {

	private Integer fundpayId;
	private User user;
	private int amountContribution;
	private int ideaId;

	public FunderPayment() {
	}

	public FunderPayment(User user, int amountContribution, int ideaId) {
		this.user = user;
		this.amountContribution = amountContribution;
		this.ideaId = ideaId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "fundpay_id", unique = true, nullable = false)
	public Integer getFundpayId() {
		return this.fundpayId;
	}

	public void setFundpayId(Integer fundpayId) {
		this.fundpayId = fundpayId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_id", nullable = false)
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@Column(name = "amount_contribution", nullable = false)
	public int getAmountContribution() {
		return this.amountContribution;
	}

	public void setAmountContribution(int amountContribution) {
		this.amountContribution = amountContribution;
	}

	@Column(name = "idea_id", nullable = false)
	public int getIdeaId() {
		return this.ideaId;
	}

	public void setIdeaId(int ideaId) {
		this.ideaId = ideaId;
	}

}
